version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: stock_market_db
    environment:
      POSTGRES_USER: "guest"
      POSTGRES_PASSWORD: "guest"
      POSTGRES_DB: "stock_market_db"
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: null # named volumes can be managed easier using docker-compose